# Project metadata
sonar.projectKey=react-python-app
sonar.projectName=React Python App
sonar.projectVersion=1.0

# Source directories
sonar.sources=frontend/src, backend

# Language-specific settings
sonar.language=js,py
sonar.sourceEncoding=UTF-8

# Exclusions (optional)
sonar.exclusions=**/node_modules/**, **/__pycache__/**

sonar.host.url=http://localhost:9000

# Test coverage (optional)
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.login=squ_200c5e27b00f6b33dddd04dc9e93de07242cff0e
