"""add_theme_preference_to_user

Revision ID: 0ef69ccabb08
Revises: da406ebe251d
Create Date: 2025-08-24 15:30:59.165348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ef69ccabb08'
down_revision: Union[str, Sequence[str], None] = 'da406ebe251d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ingredient_recipe_id'), table_name='ingredient')
    op.drop_index(op.f('idx_instruction_recipe_id'), table_name='instruction')
    op.drop_index(op.f('idx_instruction_step_number'), table_name='instruction')
    op.drop_index(op.f('idx_recipe_active'), table_name='recipe', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_recipe_favorite'), table_name='recipe', postgresql_where='(favorite = true)')
    op.drop_index(op.f('idx_recipe_slug'), table_name='recipe')
    op.drop_index(op.f('idx_recipe_title'), table_name='recipe')
    op.drop_index(op.f('idx_recipe_user_favorite'), table_name='recipe')
    op.drop_index(op.f('idx_recipe_user_id'), table_name='recipe')
    op.drop_index(op.f('idx_recipe_tags_recipe_id'), table_name='recipe_tags')
    op.drop_index(op.f('idx_recipe_tags_tag_id'), table_name='recipe_tags')
    op.drop_index(op.f('idx_tag_name'), table_name='tag')
    op.add_column('user', sa.Column('theme_preference', sa.String(), nullable=True))
    op.drop_index(op.f('idx_user_budget_preference_user_id'), table_name='user_budget_preference')
    op.drop_index(op.f('idx_user_cuisine_preference_user_id'), table_name='user_cuisine_preference')
    op.drop_index(op.f('idx_user_dietary_restriction_user_id'), table_name='user_dietary_restriction')
    op.drop_index(op.f('idx_user_health_goal_user_id'), table_name='user_health_goal')
    op.drop_index(op.f('idx_user_session_active'), table_name='user_session', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_user_session_recipe_id'), table_name='user_session')
    op.drop_index(op.f('idx_user_session_session_id'), table_name='user_session')
    op.drop_index(op.f('idx_user_session_user_id'), table_name='user_session')
    op.drop_index(op.f('idx_user_skill_level_user_id'), table_name='user_skill_level')
    op.drop_column('user_skill_level', 'id')
    op.drop_index(op.f('idx_user_tag_name'), table_name='user_tag')
    op.drop_index(op.f('idx_user_tag_user_id'), table_name='user_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_tag_user_id'), 'user_tag', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_tag_name'), 'user_tag', ['tag_name'], unique=False)
    op.add_column('user_skill_level', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('idx_user_skill_level_user_id'), 'user_skill_level', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_session_session_id'), 'user_session', ['session_id'], unique=False)
    op.create_index(op.f('idx_user_session_recipe_id'), 'user_session', ['recipe_id'], unique=False)
    op.create_index(op.f('idx_user_session_active'), 'user_session', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_user_health_goal_user_id'), 'user_health_goal', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_dietary_restriction_user_id'), 'user_dietary_restriction', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_cuisine_preference_user_id'), 'user_cuisine_preference', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_budget_preference_user_id'), 'user_budget_preference', ['user_id'], unique=False)
    op.drop_column('user', 'theme_preference')
    op.create_index(op.f('idx_tag_name'), 'tag', ['name'], unique=False)
    op.create_index(op.f('idx_recipe_tags_tag_id'), 'recipe_tags', ['tag_id'], unique=False)
    op.create_index(op.f('idx_recipe_tags_recipe_id'), 'recipe_tags', ['recipe_id'], unique=False)
    op.create_index(op.f('idx_recipe_user_id'), 'recipe', ['user_id'], unique=False)
    op.create_index(op.f('idx_recipe_user_favorite'), 'recipe', ['user_id', 'favorite'], unique=False)
    op.create_index(op.f('idx_recipe_title'), 'recipe', ['title'], unique=False)
    op.create_index(op.f('idx_recipe_slug'), 'recipe', ['slug'], unique=False)
    op.create_index(op.f('idx_recipe_favorite'), 'recipe', ['favorite'], unique=False, postgresql_where='(favorite = true)')
    op.create_index(op.f('idx_recipe_active'), 'recipe', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_instruction_step_number'), 'instruction', ['recipe_id', 'step_number'], unique=False)
    op.create_index(op.f('idx_instruction_recipe_id'), 'instruction', ['recipe_id'], unique=False)
    op.create_index(op.f('idx_ingredient_recipe_id'), 'ingredient', ['recipe_id'], unique=False)
    # ### end Alembic commands ###
