"""add_missing_user_columns

Revision ID: a7967ddfba8a
Revises: c579cfa08ea7
Create Date: 2025-08-19 21:17:57.609502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7967ddfba8a'
down_revision: Union[str, Sequence[str], None] = 'c579cfa08ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_budget_preference',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('budget_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_cuisine_preference',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dietary_restriction',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('restriction', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_health_goal',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_skill_level',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('hero_image_url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('onboarding_complete', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('how_heard_about', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'how_heard_about')
    op.drop_column('user', 'onboarding_complete')
    op.drop_column('user', 'hero_image_url')
    op.drop_column('user', 'profile_picture_url')
    op.drop_column('user', 'age')
    op.drop_table('user_skill_level')
    op.drop_table('user_health_goal')
    op.drop_table('user_dietary_restriction')
    op.drop_table('user_cuisine_preference')
    op.drop_table('user_budget_preference')
    # ### end Alembic commands ###
